export const ADD_USER_IS_LOADING = 'ADD_USER_IS_LOADING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const GET_PERFORMANCES_IS_LOADING = 'GET_PERFORMANCES_IS_LOADING';
export const GET_PERFORMANCES_SUCCESS = 'GET_PERFORMANCES_SUCCESS';
export const GET_PERFORMANCES_FAIL = 'GET_PERFORMANCES_FAIL';
