export const ADD_USER_IS_LOADING = 'ADD_USER_IS_LOADING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const UPDATE_USER_IS_LOADING = 'UPDATE_USER_IS_LOADING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const REMOVE_USER_IS_LOADING = 'REMOVE_USER_IS_LOADING';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAIL = 'REMOVE_USER_FAIL';

export const GET_PERFORMANCES_IS_LOADING = 'GET_PERFORMANCES_IS_LOADING';
export const GET_PERFORMANCES_SUCCESS = 'GET_PERFORMANCES_SUCCESS';
export const GET_PERFORMANCES_FAIL = 'GET_PERFORMANCES_FAIL';

export const GET_PERFORMANCE_BY_ID_IS_LOADING = 'GET_PERFORMANCE_BY_ID_IS_LOADING';
export const GET_PERFORMANCE_BY_ID_SUCCESS = 'GET_PERFORMANCE_BY_ID_SUCCESS';
export const GET_PERFORMANCE_BY_ID_FAIL = 'GET_PERFORMANCE_BY_ID_FAIL';

export const GET_FAVORITE_PERFORMANCES_IS_LOADING = 'GET_FAVORITE_PERFORMANCES_IS_LOADING';
export const GET_FAVORITE_PERFORMANCES_SUCCESS = 'GET_FAVORITE_PERFORMANCES_SUCCESS';
export const GET_FAVORITE_PERFORMANCES_FAIL = 'GET_FAVORITE_PERFORMANCES_FAIL';

export const GET_BESTPLACES_IS_LOADING = 'GET_BESTPLACES_IS_LOADING';
export const GET_BESTPLACES_SUCCESS = 'GET_BESTPLACES_SUCCESS';
export const GET_BESTPLACES_FAIL = 'GET_BESTPLACES_FAIL';

export const GENERATE_MEETING_POINT_IS_LOADING = 'GENERATE_MEETING_POINT_IS_LOADING';
export const GENERATE_MEETING_POINT_SUCCESS = 'GENERATE_MEETING_POINT_SUCCESS';
export const GENERATE_MEETING_POINT_FAIL = 'GENERATE_MEETING_POINT_FAIL';

export const CLEAR_ALL = 'CLEAR_ALL';
export const CLEAR_MEETING_POINT = 'CLEAR_MEETING_POINT';
